sudo: required
services:
- docker
before_install:
- docker build -t ibmmitchmakos/react-client:latest -f Dockerfile.dev .
script:
- docker run -e CI=true ibmmitchmakos/react-client:latest npm run test -- --coverage
deploy:
  provider: openshift
  user: mitchell.makos@ibm.com
  password: IBM05041992Garage$
  app: react-client
  domain: mooc-one-ocp-clus-532507-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-east.containers.appdomain.cloud
