sudo: required
services:
  - docker

before_install:
  - docker build -t ibmmitchmakos/react-client:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true ibmmitchmakos/react-client:latest npm run test -- --coverage